rpc:
  env: dev
  name: consumer
  version: 1.0.0
  host: 127.0.0.1
  port: 8082
  weight: 1
  mock: false
  serializer: kryo
  loadBalancer: random
  retryStrategy: fixedInterval
  tolerantStrategy: failFast
  registry:
    type: etcd # zookeeper
    address: "http://localhost:2379" # localhost:2181
    timeout: 5000
    leaseTime: 30
    compensationInterval: 1
