rpc:
  env: dev
  name: consumer
  version: 1.0.0
  host: 127.0.0.1
  port: 8082
  weight: 1
  mock: false
  serializer: json
  loadBalancer: random
  retryStrategy: fixedInterval
  tolerantStrategy: failFast
  registry:
    type: zookeeper
    address: "localhost:2181" # http://localhost:2379
    timeout: 5000
    leaseTime: 30
    compensationInterval: 1
