rpc:
  env: dev
  name: IUserService
  version: 1.0.0
  host: 127.0.0.1
  port: 8081
  weight: 1
  mock: false
  serializer: kryo
  registry:
    type: etcd
    address: "http://localhost:2379"
    timeout: 5000
    leaseTime: 30
