myRPC:
  env: dev
  name: MyRPC
  version: 1.0.0
  weight: 1
  mock: false
  cluster:
    registry:
      type: etcd
      address: "http://localhost:2379"
      timeout: 5000
      leaseTime: 30
    loadBalancer: consistentHash
    retryStrategy: exponentialBackoff
    tolerantStrategy: failFast
  protocol:
    serializer: kryo
  client:
    ioThreads: 16
    connectTimeout: 3000
  server:
    host: 127.0.0.1
    port: 8081
    group:
      bossThreads: 1
      workerThreads: 16
      businessThreads: 32

